#ifndef OCV_BITPLANE_HPP
#define OCV_BITPLANE_HPP

#include <opencv2/core.hpp>

#include <vector>

/*!
 *  \addtogroup ocv
 *  @{
 */
namespace ocv{

/**
 * Generate bit planes based on the input
 * @param input input image which desire to generate bit planes, the type\n
 * must be CV_8U.
 * @param output bit planes generated by the input, output[n] is equal to
 * bitset<8>(input.at<uchar>(x,y))[n] == 1 ? 1 : 0, n is within [0, 7]
 */
void bitplane_generator(cv::Mat const &input, std::vector<cv::Mat> &output);

} /*! @} End of Doxygen Groups*/

#endif // BITPLANE_HPP

